spring.application.name=PrincipleTestingPrototype

spring.datasource.url=jdbc:postgresql://localhost:5432/webshop_s1152974
spring.datasource.username=s1152974
spring.datasource.password=s1152974
server.port=8080


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


spring.web.error.include-message=always
server.servlet.context-path=/api


#jwt.secret=supderDuperSecretGoblinAmazingPasswordEncoderForTheCoolKids123**
#jwt.expiration=3600000